/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib_projekt;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author hillv
 */
public class EfterInlogg extends javax.swing.JFrame {

    private InfDB idb;
    private String epost;
    private String nuvarandeLosenord;

    /**
     * Skapar ett nytt EfterInlogg-fönster.
     */
    // Konstruktör för EfterInlogg utan e-post
    public EfterInlogg() {
        initComponents();

        // Försök att skapa en anslutning till databasen
        try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
            System.out.println("Databasanslutning lyckades");
        } catch (InfException ettUndantag) {
            // Visa felmeddelande om det uppstår problem med databasanslutningen
            JOptionPane.showMessageDialog(null, "Något gick fel vid anslutning till databasen!");
            System.out.println("Internt felmeddelande: " + ettUndantag.getMessage());
        }
    }

// Konstruktör för EfterInlogg med e-post
    public EfterInlogg(String epost, String losenord) {
        initComponents();
        this.epost = epost;
        nuvarandeLosenord = losenord;

        // Uppdatera välkomstmeddelandet med användarens e-post
        lbValkommen.setText("Välkommen, " + epost + "!");

        // Försök att skapa en anslutning till databasen
        try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
            System.out.println("Databasanslutning lyckades");
        } catch (InfException ettUndantag) {
            // Visa felmeddelande om det uppstår problem med databasanslutningen
            JOptionPane.showMessageDialog(null, "Något gick fel vid anslutning till databasen!");
            System.out.println("Internt felmeddelande: " + ettUndantag.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbValkommen = new javax.swing.JLabel();
        btnAndraLosenord = new javax.swing.JButton();
        txtNyttLosenord = new javax.swing.JTextField();
        lbAndraLosenord = new javax.swing.JLabel();
        btnRegAlien = new javax.swing.JButton();
        btnAndraAlien = new javax.swing.JButton();
        btnListaUtrustning = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbValkommen.setText("Välkommen!");

        btnAndraLosenord.setText("Ändra Lösenord");
        btnAndraLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraLosenordActionPerformed(evt);
            }
        });

        lbAndraLosenord.setText("Om du vill ändra lösenord:");

        btnRegAlien.setText("Registera Alien");
        btnRegAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegAlienActionPerformed(evt);
            }
        });

        btnAndraAlien.setText("Ändra Alien");
        btnAndraAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraAlienActionPerformed(evt);
            }
        });

        btnListaUtrustning.setText("Lista Utrustning");
        btnListaUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaUtrustningActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAndraLosenord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNyttLosenord)
                                    .addComponent(lbAndraLosenord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                .addComponent(btnRegAlien))
                            .addComponent(lbValkommen, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAndraAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListaUtrustning)
                        .addGap(72, 72, 72))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbValkommen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(lbAndraLosenord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNyttLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAndraLosenord)
                    .addComponent(btnRegAlien))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAndraAlien)
                    .addComponent(btnListaUtrustning))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAndraLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraLosenordActionPerformed

        try {
            // Hämta det nya lösenordet från textfältet
            String nyttLosenord = txtNyttLosenord.getText();

            // Kontrollera om det nya lösenordet är 6 tecken eller kortare
            if (nyttLosenord.length() <= 6) {
                // Skapa SQL-frågan för att uppdatera lösenordet i databasen
                String fraga = "UPDATE agent SET losenord ='" + nyttLosenord + "' WHERE epost = '" + epost + "'";

                // Utför uppdateringen i databasen
                idb.update(fraga);

                // Uppdatera användargränssnittet med bekräftelsemeddelande
                lbValkommen.setText("Lösenord är ändrat!");
            } else {
                // Visa felmeddelande om lösenordet är för långt
                JOptionPane.showMessageDialog(null, "För långt lösenord!");
            }
        } catch (InfException ex) {
            // Visa felmeddelande om det uppstår ett internt fel
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ex.getMessage());
        }
    }//GEN-LAST:event_btnAndraLosenordActionPerformed

    private int getAlienID(String epost, String losenord) {
        int agentID = -1;
        try {
            // Skapa SQL-frågan för att hämta Agent_ID baserat på e-post och lösenord
            String fraga = "SELECT Agent_ID FROM agent WHERE epost = '" + epost + "' AND losenord = '" + losenord + "'";

            // Utför frågan och hämta resultatet
            String svar = idb.fetchSingle(fraga);

            // Konvertera svar till int och sätt värdet för agentID
            if (svar != null && !svar.isEmpty()) {
                agentID = Integer.parseInt(svar);
            }

        } catch (InfException e) {
            // Visa felmeddelande om det uppstår ett internt fel
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + e.getMessage());
        }

        return agentID;
    }
    private void btnRegAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegAlienActionPerformed

        // Hämta agentID
        int agentID = getAlienID(epost, nuvarandeLosenord);

        // Skapa ett nytt objekt av RegNyAlien och skicka med agentID
        RegNyAlien nytt = new RegNyAlien(agentID);
        EfterInlogg.this.setVisible(false);
        nytt.setVisible(true);;
    }//GEN-LAST:event_btnRegAlienActionPerformed

    private void btnAndraAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraAlienActionPerformed
        // TODO add your handling code here:
        NamnAllaAlien nytt = new NamnAllaAlien();
        EfterInlogg.this.setVisible(false);
        nytt.setVisible(true);
    }//GEN-LAST:event_btnAndraAlienActionPerformed

    private void btnListaUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaUtrustningActionPerformed

        try {
            String agentIdQuery = "SELECT AGENT_ID FROM AGENT WHERE epost = '" + epost + "';";
            String resultatAgentID = idb.fetchSingle(agentIdQuery);
            int agentID = Integer.parseInt(resultatAgentID);

            String listaUtrustningQuery = "SELECT Benamning "
                    + "FROM utrustning, innehar_utrustning "
                    + "WHERE Agent_ID = " + agentID + " AND innehar_utrustning.Utrustnings_ID = utrustning.Utrustnings_ID";
            ArrayList<String> utrustning = idb.fetchColumn(listaUtrustningQuery);
            // Visa resultatet i ett popup-fönster
            JOptionPane.showMessageDialog(null, "Utrustning:\n" + String.join("\n", utrustning), "Lista över Utrustning", JOptionPane.INFORMATION_MESSAGE);

        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + e.getMessage());
        }


    }//GEN-LAST:event_btnListaUtrustningActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EfterInlogg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EfterInlogg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EfterInlogg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EfterInlogg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EfterInlogg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndraAlien;
    private javax.swing.JButton btnAndraLosenord;
    private javax.swing.JButton btnListaUtrustning;
    private javax.swing.JButton btnRegAlien;
    private javax.swing.JLabel lbAndraLosenord;
    private javax.swing.JLabel lbValkommen;
    private javax.swing.JTextField txtNyttLosenord;
    // End of variables declaration//GEN-END:variables
}
